name: Bug report
description: Report a reproducible defect in codex-mem
title: "[bug] <short description>"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail to reproduce quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Briefly describe the issue.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Exact steps and commands to reproduce.
      placeholder: |
        1. Run ...
        2. Configure ...
        3. Call MCP tool ...
        4. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Node/npm versions, and client (VS Code, CLI, etc.)
      placeholder: |
        OS:
        Node:
        npm:
        Client:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Share relevant output. Remove secrets before posting.
